name: Dev Tests

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@main"

      - name: "Install python"
        uses: "actions/setup-python@main"
        with:
          python-version: "3"

      - name: "Print python version"
        shell: "pwsh"
        run: "py -v"

      - name: "Install dependencies"
        shell: "pwsh"
        run: "pip install -r requirements.txt"

      - name: "Run tests"
        shell: "pwsh"
        run: "python -m unittest"
