name: Dev Tests

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@main"

      - name: "Activate venv"
        shell: "pwsh"
        run: "./venv/Scripts/activate"

      - name: "Install dependencies"
        shell: "pwsh"
        run: "pip install -r requirements.txt"

      - name: "Run tests"
        shell: "pwsh"
        run: "python -m unittest"
