name: Tests

on:
  push:
    branches: ["main", "dev"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@main"
        with:
          lfs: true

      - name: "Install python"
        uses: "actions/setup-python@main"
        with:
          check-latest: true
          python-version: "3"

      - name: "Install dependencies"
        shell: "pwsh"
        run: "pip install -r requirements.txt"

      - name: "Run tests"
        shell: "pwsh"
        run: "python -m unittest"
